- id: plants_light_off
  alias: Plants_light_off
  initial_state: 'on'
  trigger:
  - platform: sun
    event: sunrise
    offset: -36000
  action:
    service: switch.turn_off
    entity_id: switch.power_strip
- id: plants_light_on
  alias: Plants_light_on
  initial_state: 'on'
  trigger:
  - platform: sun
    event: sunrise
  action:
    service: switch.turn_on
    entity_id: switch.power_strip
- id: Sunset_lights_1
  alias: Sunset_lights_1
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  - entity_id: person.delia
    from: not_home
    platform: state
    to: home
  - entity_id: person.tom
    from: not_home
    platform: state
    to: home
  condition:
  - condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: -00:30:00
      - condition: or
        conditions:
        - condition: state
          entity_id: person.delia
          state: home
        - condition: state
          entity_id: person.tom
          state: home
  action:
  - data:
      brightness_pct: 25
      entity_id: light.living_room
      transition: 600
      kelvin: 2700
    service: light.turn_on
  initial_state: 'on'
- id: Sunset_lights_2
  alias: Sunset_lights_2
  trigger:
  - event: sunset
    offset: -00:20:00
    platform: sun
  - entity_id: person.delia
    from: not_home
    platform: state
    to: home
  - entity_id: person.tom
    from: not_home
    platform: state
    to: home
  condition:
  - condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: -00:20:00
      - condition: or
        conditions:
        - condition: state
          entity_id: person.delia
          state: home
        - condition: state
          entity_id: person.tom
          state: home
  action:
  - data:
      brightness_pct: 50
      entity_id: light.living_room
      transition: 600
      kelvin: 2700
    service: light.turn_on
  initial_state: 'on'
- id: Sunset_lights_3
  alias: Sunset_lights_3
  trigger:
  - event: sunset
    offset: -00:10:00
    platform: sun
  - entity_id: person.delia
    from: not_home
    platform: state
    to: home
  - entity_id: person.tom
    from: not_home
    platform: state
    to: home
  condition:
  - condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: -00:10:00
      - condition: or
        conditions:
        - condition: state
          entity_id: person.delia
          state: home
        - condition: state
          entity_id: person.tom
          state: home
  action:
  - data:
      brightness_pct: 75
      entity_id: light.living_room
      transition: 600
      kelvin: 2700
    service: light.turn_on
  initial_state: 'on'
- id: Sunset_lights_4
  alias: Sunset_lights_4
  trigger:
  - event: sunset
    platform: sun
  - entity_id: person.delia
    from: not_home
    platform: state
    to: home
  - entity_id: person.tom
    from: not_home
    platform: state
    to: home
  condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: person.delia
        state: home
      - condition: state
        entity_id: person.tom
        state: home
  - after: sunset
    condition: sun
  action:
  - data:
      brightness_pct: 100
      entity_id: light.living_room
      transition: 600
      kelvin: 2700
    service: light.turn_on
  initial_state: 'on'
- id: NodeMcu_motion_detected
  alias: NodeMcu_motion_detected
  trigger:
  - entity_id: binary_sensor.lolin_nodemcu_v3
    platform: state
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: -00:30:00
    - condition: sun
      before: sunrise
    - condition: numeric_state
      entity_id: sensor.kitchen_light_level
      below: 2.0
  action:
  - data_template:
      entity_id: "{% if is_state(\"input_select.nodemcu_trigger_room\", \"Living room\"\
        ) %}\n  light.living_room\n{%-elif is_state(\"input_select.nodemcu_trigger_room\"\
        , \"Kitchen\") %}\n  light.kitchen\n{%-elif is_state(\"input_select.nodemcu_trigger_room\"\
        , \"Hallway\") %}\n  light.hallway\n{%-elif is_state(\"input_select.nodemcu_trigger_room\"\
        , \"Bedroom\") %}\n  light.bedroom\n{% else %}\n  none\n{% endif %}\n"
    service: light.turn_on
- id: NodeMcu_motion_off
  alias: NodeMcu_motion_off
  trigger:
  - entity_id: binary_sensor.lolin_nodemcu_v3
    for: 00:00:10
    from: 'on'
    platform: state
    to: 'off'
  condition:
    condition: or
    conditions:
    - condition: sun
      after: sunset
      after_offset: -00:30:00
    - condition: sun
      before: sunrise
    - condition: numeric_state
      entity_id: sensor.kitchen_light_level
      below: 2.0
  action:
  - data_template:
      entity_id: "{% if is_state(\"input_select.nodemcu_trigger_room\", \"Living room\"\
        ) %}\n  light.living_room\n{%-elif is_state(\"input_select.nodemcu_trigger_room\"\
        , \"Kitchen\") %}\n  light.kitchen\n{%-elif is_state(\"input_select.nodemcu_trigger_room\"\
        , \"Hallway\") %}\n  light.hallway\n{%-elif is_state(\"input_select.nodemcu_trigger_room\"\
        , \"Bedroom\") %}\n  light.bedroom\n{% else %}\n  none\n{% endif %}\n"
    service: light.turn_off
