title: My Awesome Home
views:
    # View tab title.
  - title: Example
    # Makes the first card fill the view
    cards:
        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
      - type: map
        aspect_ratio: 100%
        default_zoom: 15
        entities:
          - device_tracker.Phone_Tom
          - zone.home